#!/bin/bash

#sudo apt-get install ros-groovy-uwsim-bullet ros-groovy-uwsim-osgbullet ros-groovy-uwsim-osgocean ros-groovy-uwsim-osgworks
#sudo apt-get install ros-hydro-uwsim-bullet ros-hydro-uwsim-osgbullet ros-hydro-uwsim-osgocean ros-hydro-uwsim-osgworks

if [ ! -d uwsim ];
then
    # Create and setup catkin workspace
    mkdir -p ./uwsim/catkin_ws/src
    pushd ./uwsim/catkin_ws/src >& /dev/null
    catkin_init_workspace
    popd >& /dev/null
    pushd ./uwsim/catkin_ws >& /dev/null
    catkin_make

    # Copy rosinstall file to workspace
    cp ../../templates/rosinstall.tpl .rosinstall

    rosws update

    #rosdep install --from-paths src --ignore-src --rosdistro groovy -y
    rosdep install --from-paths src --ignore-src --rosdistro hydro -y
    catkin_make install

    # Generate setenv.sh file on every build
    ENV_FILE_NAME="./setenv.sh"
    touch ${ENV_FILE_NAME}
    chmod +x ${ENV_FILE_NAME}
    ENV_FILE="$(readlink -f ${ENV_FILE_NAME})"

    THIS_FILE="$(readlink -f ./build.sh)"
    echo "#!/bin/bash" > ${ENV_FILE}
    echo "# DO NOT EDIT THIS FILE" >> ${ENV_FILE}
    echo "# Automatically generated from:" >> ${ENV_FILE}
    echo "# ${THIS_FILE}" >> ${ENV_FILE}
    echo "" >> ${ENV_FILE}

    # Source the setup.bash script for this project for later projects
    # that will require the current project
    PKG_ENV_FILE="$(readlink -f ./devel/setup.bash)"
    source "${PKG_ENV_FILE}"

    # Add the source line to the high-level setenv.sh script
    echo "source ${PKG_ENV_FILE}" >> ${ENV_FILE}

    echo
    echo "=================================================="
    echo "  Add the following lines to your .bashrc file    "
    echo "=================================================="
    echo
    echo "CATKIN_WS1_SETUP="${ENV_FILE}
    echo 'if [ -f ${CATKIN_WS1_SETUP} ]; then'
    echo 'source ${CATKIN_WS1_SETUP}'
    echo 'fi'
    echo 


    popd >& /dev/null

fi

